### ISSUE TITLE
Add sublicensing

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#126]
Sublicensee is a Distributor or Sales Agent company which Main Rightsholder entitles to distribute the movie or find other distributors.

## Scope

- (already implemented) sublicensee should be able to register in a dashboard normally and then undergo a normal KYC process
- on the movie page, rightsholder/sublicensee should be able to pick one of the approved distributor/sales (see Company Type) company to operate the movie distribution. That company becomes a sublicensee for the movie.
- sublicensee MAY be limited by region or time frame. [1]
- system should check if the region is not licensed already within the given time frame. Prevent adding sublicensee if the region is licensed already in the given timeframe
- sublicensee should be able to sign in into the dashboard normally
- sublicensee should be able to access a subset of rightsholder functionality namely.
  - (for all) see the revenue within licensed region
  - (only for Distributor) claim pending revenue for licensed region
  - (only for Distributor) set prices within licensed region
  - (for all) assign another sublicensee within licensed region. E.g. given X has a license to distribute in Europe, X should be able to assign company Y to distribute in Germany, but should not be able to assign distributor for Canada.
- add "My Licensees" page
  - visible to Rights Holders / Sublicensees
  - shows the list of the licenses issued by the current RH/sublicensee: company name, movie, region, timeframe

## Prerequisites

#93 should be implemented

## Roles

gardener: @troggy 150 DAI
worker: @troggy 670 DAI
reviewer: [reviewer] 80 DAI

## Related Questions/Answers

> **@troggy:**
> is sublicensing per movie or per company?
> - (per movie) RH owns titles X and Y and may assign distributor 1 to distribute X and distributor 2 to distribute Y.
> - (per company) RH assigns distributor 1 to distribute all (or many) his titles
> What is most likely scenario we should adopt user interface for? If we go with (1) then it will be tedious to assign a Distributor for situation (2) when there are many titles to distribute
> 
> **@Right2Rebel:**
> Per movie.
> However sometimes a distributor may buy the library of a RH (all their films/share of revenue of films). Still however, they would have to assign each individual film, as each films lives its own life.

> **@troggy:**
> Can we expect that Distributor and Sales Agent companies will be available in movie databases? (IMDB or TMDB)
> 
> **@Right2Rebel:**
> Yes

> **@troggy:**
> all the companies will be KYCd/approved by Admin (WhiteRabbit/Governance) or Main Rightsholder can approve his Sales Agents/Distributors?
> So to me it is either:
> a. Producer approves, we are not involved
> or
> b. We approve, producer is not involved (except he selects the approved company later on as a sublicensee)
> 
> **@Right2Rebel:**
> (b)

----

[1] E.g. Sales Agents are likely will not be restricted by region as their goal is to find regional distributors (?). Distributors are likely will be restricted by region

**Comment by troggy** [comment]
effort exceeded the budget for this bounty. I've forked out an extra size-S bounty #142 for the rest of scope

**Comment by Right2Rebel** [comment]
1. Let's ensure that a sub-licensee may receive partial regional license 
2. Let's ensure that Main RH may assign a non KYC sub-licensee and the non-KYC sub-licensee may operate as a licensee, but the KYC must happen to receive funds (I assume that might hold up all fund payment from SC)

**Comment by troggy** [comment]
@Right2Rebel 

> Let's ensure that a sub-licensee may receive partial regional license

Captured here: https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/148

> Let's ensure that Main RH may assign a non KYC sub-licensee and the non-KYC sub-licensee may operate as a licensee, but the KYC must happen to receive funds (I assume that might hold up all fund payment from SC)

Captured here https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/151

> Alternatively can non-KYC persons retain funds in distribution pool?

didn't get it. Can you elaborate?
