### ISSUE TITLE
Register Broadcasters/PSS and allow them to set prices

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#127]
Broadcasters (PSS, Cinemas etc) should be able to register in the system to be able to participate in the waterfall and set prices.

## Scope
- on Register screen:
   - add "Broadcaster" option to "Type of Role" field
- Broadcaster undergoes same KYC/approval process as all the other companies 
- on the movie License page:
  - RH/distributor should be able to create one or more licenses for the Broadcasters of the movie
  - Broadcaster license as well as a Sales/Distributor licenses may be optionally restricted to a territory/medium/timeframe
  - Broadcaster license only allows the Broadcaster to set the movie price (within their license scope)

## Prerequisites

#93 should be implemented

## Roles

gardener: @troggy 50 DAI
worker: @troggy 250 DAI
reviewer: [reviewer] 50 DAI

**Comment by Right2Rebel** [comment]
It will mostly be SALES that assign exhibitors, broadcasters and cinemas. Note we will hear have a different payment methodology. 

Question is how far should we go now (WR must be priority, not RFR functionality) - but we must plan for RFR down the road

**Comment by troggy** [comment]
I was assuming the [list](https://docs.google.com/spreadsheets/d/1oJOQc8IeXwgG1e4duLnUoZ9ZQiUdcjScWiwGtAaZF-4/edit#gid=422602947) as a priority and it mentions the listing of PSS

**Comment by troggy** [comment]
> Note we will hear have a different payment methodology.

I think we can segregate these by medium. E.g. WR can be limited to EST medium only

**Comment by Right2Rebel** [comment]
Note: 
- Suggest we simply allow RH to allow Licensee to set price, like a checkbox, which overrules RH price
- Do not call Exhibitors but Broadcaster

**Comment by troggy** [comment]
@Right2Rebel proposal is to use "Sublicensing" feature to add Broadcasters. Broadcaster is just a type of license (other types are Sales and Distribution).

Example screen (see #151 for more details):

![image](https://user-images.githubusercontent.com/163447/103866771-58075b80-50d7-11eb-9c14-14ed436c2151.png)
