### ISSUE TITLE
Movie price retrieval returns default if price has Any medium

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#138]
Given:
price Y is set for region X and Any medium
wallet queries the price for region X and medium EST

Expected:
- backend returns price Y

Actual:
- default price is returned

Specifying medium for the price record solves the issue, so it clearly not handling "Any" medium properly.
Also I suspect it would not handle "Any" region properly as well

**Comment by mwaa** [comment]
We have to change the way the backend filters regions based on changes from frontend. Currently sub regions can't be recognized hence resulting in default prices been shown.

**Comment by troggy** [comment]
> Currently sub regions can't be recognized hence resulting in default prices been shown.

I don't think it is the case: wallet always requests individual country, never the region. RFR also stores individual countries, not the regions (regions are visible only on UI, see `groupRegions` utility function which compiles the regions from individual countries).

As for the fix, I think we have to simply exclude the condition for `medium` in `findPrice` API if the medium is empty

**Comment by mwaa** [comment]
Agreed i had not seen the new changes
