### ISSUE TITLE
Companies should be limited to the scope of their license

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#142]
Extension of #126

If the company is licensed for the Movie X in the region "Europe" it should be able to set prices and issue licenses for the movie only for "Europe" or underlying countries (e.g. France, but not Canada). Same applies for a time window and medium restriction.

## Scope
- show which regions/time/medium the movie is licensed for on the Title screen (can be hidden for Producers)
- on the Movie Page:
  - show Revenue and Prices only for the licensed regions/time/medium
  - prevent adding Prices and Licenses for regions/time/medium other that licensed
  - show Sublicenses issued by given company only
  - only Distributors and Producers should be allowed to claim revenue and set prices. Sales should be allowed to issue sublicenses only
- add appropriate authorizations on the backend side as well

## Roles

gardener: @troggy 50 DAI
worker: @troggy 400 DAI
reviewer: [reviewer] 100 DAI

**Comment by Right2Rebel** [comment]
Note: we are talking about streaming. Once we enter the territory of SALES of licenses from Sales, they should be able to set the price. So we must plan ahead in this scope for a full fledged RFR. 

As of now it operates more like WR dashboard (which is fine!)

**Comment by troggy** [comment]
@Right2Rebel  You mean, Sales assigned by Producer CANNOT set price, but Sales assigned by another Sales CAN set price?
If so, what's the business meaning of this? Can you elaborate?
