### ISSUE TITLE
Licensing: allow non-KYC company 

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#151]
> Let's ensure that Main RH may assign a non KYC sub-licensee and the non-KYC sub-licensee may operate as a licensee, but the KYC must happen to receive funds (I assume that might hold up all fund payment from SC)

Proposed solution:
- RH will be able to select ANY company (as of TMDB) for the license. This way we are not blocking RH from creating the license structure in RFR.
- RH will have to select the type of License (see screenshot sketch)
- Disregarding if the company already has licenses in RFR or not, a Sales company will have to undergo the usual KYC process in order to work in RFR Portal.

![image](https://user-images.githubusercontent.com/163447/103866277-95b7b480-50d6-11eb-8c6b-19b11da96309.png)

## Scope
- on Sublicense form:
  - add "Type of License" radio button group (See screenshot example, it is a sketch not a final design)
  - change company select box to the search box like on Register Form
  - when submitted create a non-approved Company for non-existing licensees
  - when creating a license save type of license as an attribute of the License
- on Register Form:
  - for SALES companies show the list of movies licensed in RFR instead of the list from TMDB. Rationale: we can get only movies by _production company_ from TMDB, so for Sales this list will always be empty or irrelevant.
  - if the Company already exists and is not approved assign the user to it
  - reject submission, if the Company already exists and is approved;
- on Admin screen:
  - don't show approve/reject buttons for the Sales companies which have no user assigned yet (ie not onboarded yet). Prevent approval of such companies on the backend as well.
- when checking for permissions, use type of licenses instead of type of company everywhere. Both on the frontend and the backend

## Roles
gardener: @troggy 100 DAI
worker: @troggy 720 DAI
reviewer: [reviewer] 80 DAI

**Comment by Right2Rebel** [comment]
@troggy we need to clarify the scope, the text is a bit difficult to fully comprehend.

**Comment by troggy** [comment]
@Right2Rebel it is a technical task, maybe that's why. Business definition would be the following:
rightsholders/sales/distributors should be able to issue licenses for the companies which not are yet onboarded in RFR. Representatives for such companies can register in RFR later in order.

**Comment by troggy** [comment]
I've just realize that we cannot allow non-kyc companies to do anything in the RFR (e.g. issue licenses). This will be a security hole. Consider the following example:
1. RH issues a license to non-KYC company X. This company doesn't yet have representative person assigned
2. Attacker may register as a representative of Company X
3. If we allow non-KYC companies to work with RFR, attacker will be able to change data within "its license" (e.g. prices or sublicenses)

**Comment by troggy** [comment]
adjusted description to emphasize the design proposal
