### ISSUE TITLE
keep a separate address for Company's revenue

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#178]
Right now we use Responsible Person's account address to collect the revenue. Responsible Person may be just an administrator so it doesn't make sense to allow him to keep the funds and it's better to separate these concerns.

Proposed solution: use Responsible Person's account for RFR authentication only and use separate account address (per Company) for to collect claimed revenue. Someone should still hold the private key for that address (CFO?) or it may be a multisig for funds safety.

## Scope

On a Register screen:
- add "Company wallet address" text field with the description "For collected revenue. Make sure your organization has access to this account". Here WR can advertise an extra service of setting up the multisig (out of scope).
- validate the field is not empty
- validate the field contains valid Ethereum address

When claiming revenue the revenue should go to the Company address, not the address of the person.

## Roles
gardener: @troggy 50 DAI
worker: @troggy 250 DAI
reviewer: [reviewer] 50 DAI

**Comment by Right2Rebel** [comment]
- how do companies around the world handle their accounts - should we provide options? 
- How about interface for Multisigs?

**Comment by troggy** [comment]
@mwaa no definition here

**Comment by troggy** [comment]
> should we provide options?

People holding the keys in multisig should understand what it is and how to work with it. Someone should educate them about that and set up the multisig itself. This someone could be either the trusted person hired by the Company (employee) or it could be WhiteRabbit (perhaps as an extra service)
