### ISSUE TITLE
setup email sending backend

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/dashboard#205]
## Scope

- Use amazon SES service
- Add Endpoint sendEmail in graphql backend
- Get details of whiterabbit.one or ask preferred address to use e.g `info@whiterabbit.one`
- Templating approach with replaceable variables with existing data (Use graphql api data)
- Provide Simple api interface that accepts sender,receiver,message
- Ensure deployment pipeline is triggered for graphql backend

## Roles
gardener/worker @mwaa 870
reviewer: @troggy 80 DAI

**Comment by troggy** [comment]
via #203
