### ISSUE TITLE
ability to verify movie chain of title

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/dashboard#30]
## Scope

Rightsholder:
- a set of documents describing the chain of title are uploaded:
  - add Upload component on "Add Movie" page
  - upload docs to S3, keep the link private (as the S3 bucket has no access control for simplicity). 
  - only Admin should be able to see full link to the doc in S3 (make sure graphql query resolvers take care of that).
  - while the admin has taken no action on the movie, is is displayed as pending in the list, claim revenue is not available.
  - for simplicity, there will be no edit of chain of title docs after submission. In case the documents needs to be corrected, the movie is unregistered and RH have to create a new add movie request

Admin:
- In the list of registered movies the admin interface will display the request, giving the admin the option to:
- view the documents
- admin can choose to unregister a movie if documents provided don't match
- the admin will notify the rightsholder manually about either of the events, based on the contact data from the rightsholder table

## Roles

gardener/worker: @mwaa 470 DAI
reviewer: @troggy 80 DAI

**Comment by troggy** [comment]
> what happens to payments?

nothing. Kept in collecting pool. Probably should refund in case of decline, but this is subject for later versions IMO

**Comment by troggy** [comment]
On a second thought, we shouldn't refund those as long as we don't allow claims. The proper RH may come to get those payments
