### ISSUE TITLE
More fields and correct director and producer reversed?

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/dashboard#45]
## Scope
On add movie screen display additional information and make corrections

## Deliverable
- Display ISAN number
- Producer missing (previous error with Coce et Chanel was producer/director swap)
- It would be natural to display fields correlated to main rights holders + actors

> Producer(s)
> Director(s)
> Writer(s)
> Composer(s)
> Actors 
> Production Company(s)

- Please note some of this fields are too many. UI would require loaders were appropriately. Display first 10 names and have a `Show More` button to load the rest of names. 

Refrence [Screen #3](https://docs.google.com/document/d/1NcUjHBQ94PhQi1hnqfw27JayTPzqllf1DnTTzmmB2J0/edit#)

## Roles
gardener: @mwaa 30 DAI
worker: 
reviewer:

**Comment by Clearwood** [comment]
additionally not all producers are shown

**Comment by mwaa** [comment]
ISAN number not available in current api
