### ISSUE TITLE
ability to claim money from collection pool

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/dashboard#47]
Original memo as captured on the planning call (only guidance, not an action list):

> - per movie/region display of funds collected
> - have 'claim' button, and one 'return' button per movie and region

## Scope

BE:
- ~change subgraph to index `Distribution` event as well and collect amounts distributed per movie per region (similar to Deposits). See WhiteRabbitTheWorldIsYours/mad-hatter#100 and WhiteRabbitTheWorldIsYours/mad-hatter#101~ Done by @johannbarbie already

FE:
on the /Titles list
- [ ] show outstanding revenue collected per title (calculated as `total_revenue – distributed_revenue` per movie. 
- [ ] on click reveal the revenue breakdown by region (use product of #58)
- [ ] show "claim" button which triggers distribution backend (see https://github.com/WhiteRabbitTheWorldIsYours/payment-backend/issues/4). Allow RH to select which regions he wants to claim revenue for. Aggregate the revenue for selected regions and execute "distribute" multiple times if needed. Warn the RH that he will receive the money on his wallet and from that moment it is up to him to distribute them further

## Roles

gardener: @troggy 80 DAI
worker: @troggy
reviewer: @johannbarbie

**Comment by Clearwood** [comment]
in what case and to whom would a return button be displayed considering that rightsholders would register a movie?

**Comment by troggy** [comment]
@johannbarbie @mwaa @Clearwood I guess we will need to index events here with [Graph Protocol software](https://thegraph.com/) (like in MolochDAO) ?

**Comment by troggy** [comment]
forked out subgraph creation bounty: https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/57

**Comment by troggy** [comment]
how can we know how much the RH can claim as we are not recording previous claims per region anywhere?

**Comment by troggy** [comment]
related WhiteRabbitTheWorldIsYours/mad-hatter#100

**Comment by johannbarbie** [comment]
> in what case and to whom would a return button be displayed considering that rightsholders would register a movie?

In the simple first case only the admin can send back funds. also only funds that are older than x days and don't have a verified rightsholder.

**Comment by troggy** [comment]
"Return" is implemented per payment, not per region and thus it not trivial to implement. I suggest to fork this feature out of this bounty so we don't blow the scope

**Comment by troggy** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/163447/85010327-825bf080-b168-11ea-8700-d1b1e05b3c4b.png">

**Comment by johannbarbie** [comment]
paid out:  https://etherscan.io/tx/0x8e39482fea6750c79c7a26fa76ad266301be86b538ce501c2ccf8180ff21ae47
