### ISSUE TITLE
Reconcile imdb id

### ISSUE THREAD

**Issue by mwaa** [WhiteRabbitTheWorldIsYours/dashboard#48]
## Scope

Please note tt2380307 is not the same movie as 2380307. 
`tt {int}` IMDB ID
`plain int` TMDB API ID

Coco 2017 Animation
For the public website [tt2380307 ](https://www.imdb.com/title/tt2380307) will have `tt` but api will never have this with equivalent api id `354912`

tt2380307 is still valid though we would have to check for api id to avoid duplicates of the same movie against TMDB api 354912.

## Deliverable
- restrict to using tt2380307 since this available to public. retrieve value from api
- add validation check that record with TMDB id does not exist before insert using IMDB id
- if IMDB id is missing then save record using TMDB ID with source will change to `TMDB` instead of IMDB change BE to account for this

## Roles
gardener: @mwaa 50 DAI
worker: @mwaa 80%
reviewer: [reviewer] 20%

**Comment by troggy** [comment]
I think `354912` is the ID of themoviedb.org. TheMovieDB is not affiliated with IMDB and is rather an aggregator, probably that's why they have their own id.

> Maybe restrict to tt2380307 since this available to public try see if we can get this value from the api

Yes, I'd always use IMDB ids for everything

**Comment by mwaa** [comment]
Assumption since streamer will always send IMDB ID then would have to have a function to capture movies that exist on IMDB but don't exist on TMDB api

**Comment by troggy** [comment]
I don't understand this bounty. Isn't it enough to just change this line here: https://github.com/WhiteRabbitTheWorldIsYours/dashboard/blob/master/frontend/src/stores/API.ts#L86

to be `id: current.imdb_id` ? (there is always imdb_id in TMDB query results)

**Comment by mwaa** [comment]
Agreed its as simple as changing the single line. This ticket is more to account for scenario when imdb_id is missing. Maybe not needed in current sprint

![2020-06-12-13-18-developers themoviedb org](https://user-images.githubusercontent.com/5112468/84492698-3fed6c00-acaf-11ea-90f4-494086374371.png)

**Comment by troggy** [comment]
now I understand what you mean — stumbled across `person` entries in TMDB without `imdb_id` present. If we ever encounter the same for `movie` entry it will be a problem.

**Comment by mwaa** [comment]
Saving record if imdb_id exists only. Showing error if user tries to save without imdb_id
