### ISSUE TITLE
after personal register screen, show list of movies

### ISSUE THREAD

**Issue by johannbarbie** [WhiteRabbitTheWorldIsYours/dashboard#55]
## Scope

on /Register screen:
- rename "Legal Name" field to "Legal Name or IMDB ID"
- once the user typed in something in the "Legal Name or IMDB" field:
   - ~if it is an IMDB (number, optionally prefixed with `nm`). Look it up on on IMDB/TMDB using [/people/<id> API](https://developers.themoviedb.org/3/people/get-person-details).~ @troggy: Not working well for some people (TMDB doesn't have IMDB for all the people)
   - if it is the name, look it up on IMDB/TMDB using [/search_people API](https://developers.themoviedb.org/3/search/search-people)
- if there is no match — show the error "We cannot find you on IMDB. Please check spelling"
- if there is a multiple matches in IMDB/TMDB — show the list of suggestions similar like on "Add Movie" screen, but for people. So that user can pick which record is his.
- once there is a selection (or a single match in a search), show the list of movies the user is invovled in according to IMDB/TMDB (use `known_for` attribute of the above API calls results). Show "involved as" as well

## Roles

gardener: @troggy 50 DAI
worker: @troggy
reviewer: @mwaa

**Comment by troggy** [comment]
> show collection pool statistics about those movies (known_for in person query)

this requirement needs ability to collect revenue per movie (which is probably a part of #47). Forked out here: https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/56

**Comment by Clearwood** [comment]
![image](https://user-images.githubusercontent.com/11144110/84398900-ca2ac700-ac00-11ea-9e99-dbeead97d7cc.png)

**Comment by troggy** [comment]
themoviedb.org doesn't have IMDB id for some people (like Alan 🤦‍♂️). Will be using IMDB native suggestion API (unofficial?)
