### ISSUE TITLE
show revenue per movie on register screen

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#56]
## Prerequisites

Requires these to be implemented first: #57, #55

## Scope

- when showing list of movies on /Register screen (as implemented in #55), display a collected revenue per movie per region (as implemented in #57)

## Roles

gardener: @troggy 20 DAI
worker: @troggy 
reviewer: [reviewer]

**Comment by Clearwood** [comment]
![image](https://user-images.githubusercontent.com/11144110/84398985-e4fd3b80-ac00-11ea-87b7-0bab75fc0d95.png)
