### ISSUE TITLE
Create Subgraph for collection pool contract

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#57]
## Scope

- [create a Subgraph](https://thegraph.com/docs/define-a-subgraph) to index `Deposit` events of Collection Pool
- [deploy it on thegraph hosted service](https://thegraph.com/docs/deploy-a-subgraph)
- create docs on how to query from FE

## Deliverables

- new `subgraph` package in this repo
- deployed subgraph on Graph Protocol Hosted Service
- integration docs (as simple as README record or comments in the code)

## Roles

gardener: @troggy 50 DAI
worker: @Clearwood
reviewer: [reviewer] 15 %

**Comment by Clearwood** [comment]
Do you think we should create a new repo for this task?

**Comment by troggy** [comment]
I think the new package in this repo is enough (similar to `backend` and `frontend` we have right now)

**Comment by johannbarbie** [comment]
here is the moloch example: https://github.com/MolochVentures/moloch-monorepo/tree/master/packages/subgraph

**Comment by Clearwood** [comment]
thx for sharing @johannbarbie I am really in love with this

**Comment by Clearwood** [comment]
![image](https://user-images.githubusercontent.com/11144110/84399480-33aad580-ac01-11ea-842b-15ef47a70532.png)
