### ISSUE TITLE
Movie search should show RH's movies by default and allow adding movies in bulk

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#79]
## Scope
On movie search page display a list of movies belonging to RightsHolder
Unless RH have used the search form, he should see the list of the movies where he is "Producer".
Also note display movies by production company if RH is not a person as per task #93 

## Deliverable
- Fetch list of movies where RH is producer or movies are made by the company
- On load of search page show above list of movies by default
- Helper text for multi-select rows if RH has no movie records saved under them
- Modify table to allow multi select of rows for addition to GraphQL. 
- Show upload button more than one row is selected connect to new multi-upload endpoint
- Show notification that with multi-upload edit is not possible

**GraphQL AddMovie**
- Add new endpoint to bulk upload the movie entries.
- Loop through array of movie to create record for each in the the database

## Roles
gardener: @mwaa 50 DAI
worker: 
reviewer:

**Comment by troggy** [comment]
> Show upload button

is this requires #18 to be implemented first?

**Comment by mwaa** [comment]
True it would require #30 to be implemented. 
We can have the button at this stage then have functionality tied in later since this has higher priority

**Comment by troggy** [comment]
closed in favor of #120 + #30
