### ISSUE TITLE
price query is not working without time window

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#84]
**Given:**
1. Create a price of X for region 276 and EST medium
2. Execute `price` query

**Expected:**
returned json contains price X

**Actual:**
returned json contains default value (0.02)

**Comment by mwaa** [comment]
@troggy could you confirm if this happens via call from igraphql client `/graphql` or from mad-hatter

**Comment by troggy** [comment]
@mwaa both. I get default price in playground `/graphql` and in mad-hatter

```graphql
{
  price(filter: { 
    IMDB: "tt2133196",
    region: "276",
    medium: "EST" 
  }){
    amount
  }
}
```

<img width="712" alt="image" src="https://user-images.githubusercontent.com/163447/85205186-584e2e00-b322-11ea-8373-930735fdc2b0.png">


Movie id is correct: if I use the same attributes but with time window, the request works as expected
