### ISSUE TITLE
RH can be a company

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#93]
From [doc](https://docs.google.com/document/d/1NcUjHBQ94PhQi1hnqfw27JayTPzqllf1DnTTzmmB2J0/edit#)
~Support IMDB ids for company (`coXXXXX`)~. Lookup production company by name

## Scope

- on registration screen change "Legal Name" field to "Your Name"
- add new field "Company Name" which looks up the name in the TMDB:
  - Implement function to `searchCompanyInTMDB` that provides company name ~plus imdbID for the company~. Use `searchCompany` [endpoint](https://developers.themoviedb.org/3/search/search-companies) internally. _@troggy: There is no way we can get IMDB ID for the company (unless we scrape IMDB which is illegal), so we opt to use TMDB id only_
  - If the entered name could not be found, allow user to use it. E.g. by showing a special dropdown option like «Use "Whatever Inc." as a Company Name»
- `MovieListWithRevenue` component should use `discover/movie` with `with_companies` [API call](https://developers.themoviedb.org/3/discover/movie-discover), so that we show the movies by the production company.
- Update values in "Type of Role" to [Producer, Sales Agent, Distributor, Finance, Public Institution, Other]
- Should also address #118 

## Roles
gardener: @troggy 100 DAI
worker: @troggy 370 DAI
reviewer: [reviewer] 80 DAI

**Comment by troggy** [comment]
> Add field of Role Type or Company Business options are [Production, Sales, Distribution, Financing, Public Institution, Other]

already added in #92, just need to change the label

**Comment by johannbarbie** [comment]
how is the admin supposed to verify a company? how does she know that the contact person has legal permission to act for the company? is the verified address an account or a multisig?

**Comment by troggy** [comment]
> how is the admin supposed to verify a company? how does she know that the contact person has legal permission to act for the company?

I guess the same way as verifying the person — contact the person/company out-of-band and get the confirmation

> is the verified address an account or a multisig?

cannot be multisig, I guess. Otherwise, how to work with the RH dashboard 🤷‍♂️

**Comment by troggy** [comment]
My best guess is that "Company" really means "A company representative" so it is a person who has permissions to represent the Company in WhiteRabbit. Pretty sure it will be the same for most of the producers as well. Sounds dangerous to me, but I don't believe producers themselves will be installing metamask, creating backups etc

**Comment by johannbarbie** [comment]
i have a feeling that this needs be thought through much more. Until then i would not continue down the route.

at least there should be a verification protocol that the admin needs to follow based on the different types of accounts (individual, company).
cc @Right2Rebel

**Comment by Right2Rebel** [comment]
Company DOES NOT mean company representative. Most often, the true owner of the Rights is a Production Company not a Producer. The Producer is the responsible Person, but not the owning entity. 

Hence we should separate between Producers who might go from company to company and be the Responsible Person and Rights that stay with one and several other companies over a longer period of tine. 

In terms of Directors, Authors, Composers (Royalties) these might be member organisations like SACD in France, Agents like WME in USA or Individual Persons (the Director, Author or Composer)

**Comment by troggy** [comment]
there is no API to "get list of films by company". TMDB doesn't support that, IMDB has no public API at all, OMDB works only with movies (no companies).

TMDB has HTML page with the desired output. E.g. https://www.themoviedb.org/company/23437-k5-films/movie

I've started a thread with them to see if the same is available through API: https://www.themoviedb.org/talk/5f84426469eb900039c48872

**Comment by troggy** [comment]
@Right2Rebel 
1. Should we still support the case when rightsholder is a person, not a company?
2. If rightsholder is a company, do we need to capture the name of responsible person filling the form? I suspect this may be needed for the verification. So far we have only his account address

**Comment by troggy** [comment]
@Right2Rebel Nevermind the second question. I see the answer in the alpha testing doc
