### ISSUE TITLE
update copy text on Register screen

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#94]
From [Screen #2](https://docs.google.com/document/d/1NcUjHBQ94PhQi1hnqfw27JayTPzqllf1DnTTzmmB2J0/edit#):

"Sit tight and you will be contacted by the [Mad Hatter] to verify your identity. This process normally takes X hours/days but we’ll get in touch as soon as possible"

**Comment by mwaa** [comment]
Too small for bounty. Should be Implemented in #93
