### ISSUE TITLE
Display crew and cast on the Movie page and on the Add Movie page

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#95]
From [Screen #3b](https://docs.google.com/document/d/1NcUjHBQ94PhQi1hnqfw27JayTPzqllf1DnTTzmmB2J0/edit#):

On Movie Page show:
- Producer(s)
- Director(s)
- Writer(s)
- Composer(s)
- Actors 
- Production Company(s)

Add Writers and Composers to "Add Movie" page.

Note on implementation:
- we will have to store movie crew (so far we store only movie details)

**Comment by mwaa** [comment]
Ticket should handle the saving of directors and crew. The display is already been handled in #45

**Comment by troggy** [comment]
via #111
