### ISSUE TITLE
Region selection: add ability to choose region (e.g. Europe) as well as individual country

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#97]
## Scope
Changes to addition of price information.
Alan confirmed it is not clear right now, that empty region means "any region". We should clarify that on UI. vuulr.com (the reference site Alan used in the [doc](https://docs.google.com/document/d/1NcUjHBQ94PhQi1hnqfw27JayTPzqllf1DnTTzmmB2J0/edit#)) uses the term GLOBAL for this.

## Deliverable
- RH selects region (e.g. Europe) → we show all the European countries in the multi-select box already selected → RH can remove some of them or leave unchanged (thus covering whole region)
- Use [UN-M49 geographic regions](https://unstats.un.org/unsd/methodology/m49/) e.g Eastern Europe

![2020-06-30-13-35-unstats un org](https://user-images.githubusercontent.com/5112468/86117027-01d9b000-bad7-11ea-83ff-ed3a3831128c.png)

- Rename DEFAULT to GLOBAL then allow user to deselect regional areas they don't have access
- Please note if user chooses GLOBAL, then multi-select would have to show regions and not countries
- Pay attention to un-selected countries in a region. Should be available in edit mode allow user to add more to selection.
- (optional) consider making this a reusable component as we will need very similar functionality for #126 

**GraphQL Price Changes**
- Add new optional field countryRegions stores array of M49 countries in a geographic region
- Modify add price to check if array of regions is sent and create. 
- Change findPrice query to account for M49 code been in array of countryRegions

## Roles
gardener: @mwaa 50 DAI
worker: troggy 420 DAI
reviewer: [reviewer] 80 DAI

**Comment by Right2Rebel** [comment]
It would be useful to have ALL COUNTRIES EXCEPT X, Y or Z. (Often the deals are excluding only a handful "home territories" of the producer.

**Comment by troggy** [comment]
@Right2Rebel I believe this should be covered by this

> RH selects region (e.g. Europe) → we show all the European countries in the multi-select box already selected → RH can remove some of them or leave unchanged (thus covering whole region)

**Comment by troggy** [comment]
@mwaa I've exceeded the size of this bounty already, so there will be one more small bounty to make a price form and backend change.

Complete part can be reviewed here: #134 (reusable component for region selection)

**Comment by troggy** [comment]
forked out a follow up bounty https://github.com/WhiteRabbitTheWorldIsYours/dashboard/issues/135
