### ISSUE TITLE
Pricing page: rename DEFAULT region option to GLOBAL

### ISSUE THREAD

**Issue by troggy** [WhiteRabbitTheWorldIsYours/dashboard#98]
Alan confirmed it is not clear right now, that empty region means "any region". We should clarify that on UI. vuulr.com (the reference site Alan used in the [doc](https://docs.google.com/document/d/1NcUjHBQ94PhQi1hnqfw27JayTPzqllf1DnTTzmmB2J0/edit#)) uses the term GLOBAL for this.

**Comment by mwaa** [comment]
Closing to be handle as part of #97 
Too small to exist on its own
